import OpenAI from 'openai';

const openai = new OpenAI({
    apiKey: process.env.OPENAI_API_KEY,
});

export default async function handler(req, res) {
    // CORS Headers
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

    if (req.method === 'OPTIONS') {
        return res.status(200).end();
    }

    if (req.method !== 'POST') {
        return res.status(405).json({ success: false, error: 'Method not allowed' });
    }

    try {
        const { prompt } = req.body;

        if (!prompt || prompt.trim().length < 3) {
            return res.status(400).json({ success: false, error: 'Please enter at least 3 characters' });
        }

        console.log('🎨 Generating image with ChatGPT...');

        // ============================================
        // CHATGPT IMAGES 2.0 - BEST QUALITY
        // ============================================
        const response = await openai.images.generate({
            model: "gpt-image-2",
            prompt: prompt.trim(),
            n: 1,
            size: "1024x1024",
            quality: "high",
        });

        const imageUrl = response.data[0].url;

        console.log('✅ Image generated by ChatGPT!');

        return res.status(200).json({
            success: true,
            image: imageUrl,
            prompt: prompt.trim(),
            api: 'ChatGPT Images 2.0',
            message: '✅ Generated with ChatGPT!'
        });

    } catch (error) {
        console.error('❌ ChatGPT Error:', error);
        return res.status(500).json({
            success: false,
            error: error.message || 'ChatGPT API error'
        });
    }
}
